---
version: 1
 
build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest'
  EE_BUILDER_IMAGE: 'fbraz3/ansible-builder'
  PKGMGR_PRESERVE_CACHE: 'always'
 
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
 
additional_build_steps:
  append:
    - RUN microdnf -y install which net-tools
