collections:
  - name: ansible.posix
  - name: community.zabbix
  - name: community.general
  - name: community.vmware
  - name: dseeley.esxifree_guest
  - name: oracle.oci
  - name: community.digitalocean

roles:
  - name: geerlingguy.php
  - name: benjamin-smith.ondrej-php-repo
